backend:
  name: git-gateway
  branch: master
  repo: productmindset/site

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
  - name: benefits
    label: Benefits
    label_singular: Benefit
    folder: content/benefits
    create: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: false, widget: hidden}
      - { name: type, label: Type, default: benefit, widget: hidden}
      - { name: active, label: Active, default: true, widget: boolean }
      - { name: title, label: Short Name (Unique), widget: string }
      - { name: fullTitle, label: Full Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: sortOrder, label: Sort Order, valueType: int, widget: number }
      - { name: image, label: Image, widget: image }

  - name: footer
    label: Footers
    label_singular: Footer
    create: false
    delete: false
    files:
      - label: "Page Footer"
        name: "pagefooter"
        file: "content/pagefooter.md"
        fields:
          - { name: image, label: Image, widget: image, required: false }

  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: true, widget: hidden}
      - { name: templateKey, label: Template Key, default: page, widget: hidden}
      - { name: includeLearnMore, label: Include Learn More Call to Action, default: false, widget: boolean}
      - { name: path, label: Path, widget: string, required: false}
      - { name: title, label: Title, widget: string }
      - { name: heroTitle, label: Hero Title, widget: string }
      - { name: heroSubtitle, label: Hero Subtitle, widget: string }
      - { name: heroImage, label: Hero Image, required: false, widget: hidden }
      - { name: heroIsVideo, label: Hero Video, widget: boolean, default: false }
      - { name: subColumns, label: Sub Columns, widget: number, default: 2, valueType: int }
      - { name: body, label: Body, widget: markdown }

  - name: resources
    label: Resources
    label_singular: Resource
    folder: content/resources
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: false, widget: hidden}
      - { name: type, label: Type, default: resource, widget: hidden}
      - { name: active, label: Active, default: true, widget: boolean }
      - { name: resourceType, label: Resource Type, widget: string }
      - { name: title, label: Short Name (Unique), widget: string }
      - { name: fullTitle, label: Full Title, widget: string }
      - { name: url, label: URL, widget: string }
      - { name: buttonText, label: Button Text, widget: string }
      - { name: buttonFAIcon, label: Button FA Icon, widget: fontawesome }
      - { name: description, label: Description, widget: text }
      - { name: sortOrder, label: Sort Order, valueType: int, widget: number }
      - { name: image, label: Image, widget: image }
      - { name: more, label: More, widget: markdown, required: false }

  - name: speakers
    label: Speakers
    label_singular: Speaker
    folder: content/speakers
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: false, widget: hidden}
      - { name: type, label: Type, default: speaker, widget: hidden}
      - { name: active, label: Active, default: true, widget: boolean }
      - { name: title, label: Short Name (Unique), widget: string }
      - { name: fullName, label: Full Name, widget: string }
      - { name: jobTitle, label: Title, widget: string }
      - { name: company, label: Company, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: sortOrder, label: Sort Order, valueType: int, widget: number }
      - { name: image, label: Image, widget: image }

  - name: workshops
    label: Workshops
    label_singular: Workshop
    folder: content/workshops
    create: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: false, widget: hidden}
      - { name: type, label: Type, default: workshop, widget: hidden}
      - { name: active, label: Active, default: true, widget: boolean }
      - { name: title, label: Short Name (Unique), widget: string }
      - { name: fullTitle, label: Full Title, widget: string }
      - { name: time, label: Time, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: sortOrder, label: Sort Order, valueType: int, widget: number }
      - { name: image, label: Image, widget: image }
