backend:
  name: git-gateway
  branch: master
  repo: product-mindset/site

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: true, widget: hidden}
      - { name: templateKey, label: Template Key, default: page, widget: hidden}
      - { name: path, label: Path, widget: string, required: false}
      - { name: title, label: Title, widget: string }
      - { name: heroTitle, label: Hero Title, widget: string }
      - { name: heroSubtitle, label: Hero Subtitle, widget: string }
      - { name: heroImage, label: Hero Image, required: false, widget: hidden }
      - { name: heroIsVideo, label: Hero Video, widget: boolean, default: false }
      - { name: body, label: Body, widget: markdown }

  - name: speakers
    label: Speakers
    label_singular: Speaker
    folder: content/speakers
    create: true
    slug: "{{slug}}"
    fields:
      - { name: isPage, label: Is Page, default: false, widget: hidden}
      - { name: type, label: Type, default: speaker, widget: hidden}
      - { name: title, label: Short Name (Unique), widget: string }
      - { name: fullName, label: Full Name, widget: string }
      - { name: jobTitle, label: Title, widget: string }
      - { name: company, label: Company, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: sortOrder, label: Sort Order, valueType: int, widget: number }
      - { name: image, label: Image, widget: image }
